name: ecommerence
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  intl_phone_number_input: ^0.7.5
  flutter_riverpod: ^2.5.1
  dio: ^5.9.0
  flutter_secure_storage: ^10.0.0
  go_router: ^17.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4


# ----- Flutter Native Splash Configration -----
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_logo/splash_logo.png
  android: true
  ios: true

  android_12:
    color: "#ffffff"
    image: assets/images/splash_logo/splash_logo.png

# ----- Flutter Launch Icons Configration -----

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/launch_icon/launch_logo.png
  adaptive_icon_background: "#FFFFFF"

flutter:
  assets:
    - assets/images/

  uses-material-design: true
